defaults: &defaults
  cuda_device: -1
  seed: 1
  training: &training_defaults
    lr_model: 0.0001
    lr_classifier: 0.001
    warmup_rate: 0.1
  model: &model_defaults
    encoder: &encoder_defaults
      hidden_size: 384
      num_layers: 2
      bidirectional: True
      batch_first: True
    decoder: &decoder_defaults
      tag_repr_dim: 256
      arc_repr_dim: 256
      dropout: 0.2
    layer_dropout: 0.1

nl_lassysmall_test:
  <<: *defaults
  output_dir: outputs/nld_test
  training:
    <<: *training_defaults
    epochs: 1
    num_steps_per_epoch: 643
  dataset:
    name: nl_lassysmall
    splits:
      train: train
      dev: validation
      test: test
    load_batch_size: 9

hu_szeged_test:
  <<: *defaults
  output_dir: outputs/hun_test
  training:
    <<: *training_defaults
    epochs: 1
    num_steps_per_epoch: 91
  dataset:
    name: hu_szeged
    splits:
      train: train
      dev: validation
      test: test
    load_batch_size: 10


hu_to_nl_finetune:
  <<: *defaults
  output_dir: outputs/hu_to_nl_finetune
  model:
    <<: *model_defaults
    finetune_on: outputs/hun_test/model.pkl

  training:
    <<: *training_defaults
    epochs: 1
    num_steps_per_epoch: 643

  dataset:
    name: nl_lassysmall
    splits:
      train: train
      dev: validation
      test: test
    load_batch_size: 9