### Basic anchors
defaults: &defaults
  cuda_device: 0
  seed: 1
  enable_wandb: false

training_defaults: &training_defaults
  batch_size: 8
  lr_model: 0.0001
  lr_classifier: 0.0005
  scheduler: cosine
  weight_decay: 0.01
  warmup_rate: 0.1
  freeze_classifier: false
  freeze_bert: false
  freeze_bert_until: 0

model_defaults: &model_defaults
  decoder:
    tag_repr_dim: 256
    arc_repr_dim: 768
    dropout: 0.2
  layer_dropout: 0.1

wandb_defaults: &wandb_defaults
  project: ai-thesis
  entity: entity-name

### Stage-specific defaults
dataset_stage2_common: &dataset_stage2_common
  splits:
    train: train
    dev: validation
    test: test
  samples_train: 10000
  samples_dev: 500
  number_of_updates: &stage2_updates 300

dataset_stage3_common: &dataset_stage3_common
  splits:
    train: train
    dev: dev
    test: test
  samples_train: 50
  samples_dev: 25
  number_of_updates: &stage3_updates 100

### Stage/language-specific defaults
stage2_nld_spec: &stage2_nld_spec
  training:
    <<: *training_defaults
    total_updates: *stage2_updates
  dataset:
    <<: *dataset_stage2_common
    name: nl_alpino

stage2_swe_spec: &stage2_swe_spec
  training:
    <<: *training_defaults
    total_updates: *stage2_updates  
  dataset:
    <<: *dataset_stage2_common
    name: sv_talbanken

stage2_ces_spec: &stage2_ces_spec
  training:
    <<: *training_defaults
    total_updates: *stage2_updates  
  dataset:
    <<: *dataset_stage2_common
    name: cs_cac

stage2_hun_spec: &stage2_hun_spec
  training:
    <<: *training_defaults
    total_updates: *stage2_updates  
  dataset:
    <<: *dataset_stage2_common
    name: hu_szeged

stage2_nob_spec: &stage2_nob_spec
  training:
    <<: *training_defaults
    total_updates: *stage2_updates  
  dataset:
    <<: *dataset_stage2_common
    name: no_bokmaal

stage2_fin_spec: &stage2_fin_spec
  training:
    <<: *training_defaults
    total_updates: *stage2_updates  
  dataset:
    <<: *dataset_stage2_common
    name: fi_tdt

stage3_gsw_spec: &stage3_gsw_spec
  training:
    <<: *training_defaults
    total_updates: *stage3_updates
  dataset:
    <<: *dataset_stage3_common
    name: data/gsw/gsw_uzh-ud

stage3_fao_spec: &stage3_fao_spec
  training:
    <<: *training_defaults
    total_updates: *stage3_updates
  dataset:
    <<: *dataset_stage3_common
    name: data/fao/fo_oft-ud

stage3_hsb_spec: &stage3_hsb_spec
  training:
    <<: *training_defaults
    total_updates: *stage3_updates
  dataset:
    <<: *dataset_stage3_common
    name: data/hsb/hsb_ufal-ud

stage3_vep_spec: &stage3_vep_spec
  training:
    <<: *training_defaults
    total_updates: *stage3_updates
  dataset:
    <<: *dataset_stage3_common
    name: data/vep/vep_vwt-ud

hpt_test:
  <<: *defaults
  output_dir: outputs/hp_sweep_test
  training:
    <<: *training_defaults
    total_updates: 100
    batch_size: 5
    freeze_bert: true
    num_frozen_epochs: 1
  dataset:
    splits:
      train: train
      dev: validation
      test: test
    samples_train: 100
    samples_dev: 10
    name: pt_gsd
  model:
    <<: *model_defaults
  wb:
    <<: *wandb_defaults

hyperpar_tuning:
  <<: *defaults
  output_dir: outputs/hp_sweep
  training:
    <<: *training_defaults
    total_updates: 95000
    batch_size: 5
    freeze_bert: true
    num_frozen_epochs: 1
  dataset:
    splits:
      train: train
      dev: validation
      test: test
    samples_train: 9500
    samples_dev: 1000
    name: pt_gsd
  model:
    <<: *model_defaults
  wb:
    <<: *wandb_defaults

### First stage argument (use this)
first_stage_deu:
  <<: *defaults
  output_dir: outputs/1_deu
  training:
    <<: *training_defaults
    total_updates: 1800000
    batch_size: 5
    freeze_bert: true
    num_frozen_epochs: 1
  dataset:
    splits:
      train: train
      dev: validation
      test: test
    samples_train: 150000
    samples_dev: 18000
    name: de_hdt
  model:
    <<: *model_defaults
  wb:
    <<: *wandb_defaults

### Second stage arguments (use these)
second_stage_nld:
  <<: [*defaults, *stage2_nld_spec]
  output_dir: outputs/2_nld
  model:
    <<: *model_defaults
    finetune_on: outputs/1_deu/model.pkl
  wb:
    <<: *wandb_defaults

second_stage_swe:
  <<: [*defaults, *stage2_swe_spec]
  output_dir: outputs/2_swe
  model:
    <<: *model_defaults
    finetune_on: outputs/1_deu/model.pkl
  wb:
    <<: *wandb_defaults

second_stage_ces:
  <<: [*defaults, *stage2_ces_spec]
  output_dir: outputs/2_ces
  model:
    <<: *model_defaults
    finetune_on: outputs/1_deu/model.pkl
  wb:
    <<: *wandb_defaults

second_stage_hun:
  <<: [*defaults, *stage2_hun_spec]
  output_dir: outputs/2_hun
  model:
    <<: *model_defaults
    finetune_on: outputs/1_deu/model.pkl
  wb:
    <<: *wandb_defaults

second_stage_nob:
  <<: [*defaults, *stage2_nob_spec]
  output_dir: outputs/2_nob
  model:
    <<: *model_defaults
    finetune_on: outputs/1_deu/model.pkl
  wb:
    <<: *wandb_defaults

second_stage_fin:
  <<: [*defaults, *stage2_fin_spec]
  output_dir: outputs/2_fin
  model:
    <<: *model_defaults
    finetune_on: outputs/1_deu/model.pkl
  wb:
    <<: *wandb_defaults

### Third stage arguments (use these)
third_stage_nld_gsw:
  <<: [*defaults, *stage3_gsw_spec]
  output_dir: outputs/3_nld_gsw
  model:
    <<: *model_defaults
    finetune_on: outputs/2_nld/model.pkl

third_stage_nld_fao:
  <<: [*defaults, *stage3_fao_spec]
  output_dir: outputs/3_nld_fao
  model:
    <<: *model_defaults
    finetune_on: outputs/2_nld/model.pkl
  wb:
    <<: *wandb_defaults

third_stage_nld_hsb:
  <<: [*defaults, *stage3_hsb_spec]
  output_dir: outputs/3_nld_hsb
  model:
    <<: *model_defaults
    finetune_on: outputs/2_nld/model.pkl
  wb:
    <<: *wandb_defaults

third_stage_nld_vep:
  <<: [*defaults, *stage3_vep_spec]
  output_dir: outputs/3_nld_vep
  model:
    <<: *model_defaults
    finetune_on: outputs/2_nld/model.pkl
  wb:
    <<: *wandb_defaults

third_stage_nob_gsw:
  <<: [*defaults, *stage3_gsw_spec]
  output_dir: outputs/3_nob_gsw
  model:
    <<: *model_defaults
    finetune_on: outputs/2_nob/model.pkl
  wb:
    <<: *wandb_defaults

third_stage_nob_fao:
  <<: [*defaults, *stage3_fao_spec]
  output_dir: outputs/3_nob_fao
  model:
    <<: *model_defaults
    finetune_on: outputs/2_nob/model.pkl
  wb:
    <<: *wandb_defaults

third_stage_nob_hsb:
  <<: [*defaults, *stage3_hsb_spec]
  output_dir: outputs/3_nob_hsb
  model:
    <<: *model_defaults
    finetune_on: outputs/2_nob/model.pkl
  wb:
    <<: *wandb_defaults

third_stage_nob_vep:
  <<: [*defaults, *stage3_vep_spec]
  output_dir: outputs/3_nob_vep
  model:
    <<: *model_defaults
    finetune_on: outputs/2_nob/model.pkl
  wb:
    <<: *wandb_defaults

third_stage_ces_gsw:
  <<: [*defaults, *stage3_gsw_spec]
  output_dir: outputs/3_ces_gsw
  model:
    <<: *model_defaults
    finetune_on: outputs/2_ces/model.pkl
  wb:
    <<: *wandb_defaults

third_stage_ces_fao:
  <<: [*defaults, *stage3_fao_spec]
  output_dir: outputs/3_ces_fao
  model:
    <<: *model_defaults
    finetune_on: outputs/2_ces/model.pkl
  wb:
    <<: *wandb_defaults

third_stage_ces_hsb:
  <<: [*defaults, *stage3_hsb_spec]
  output_dir: outputs/3_ces_hsb
  model:
    <<: *model_defaults
    finetune_on: outputs/2_ces/model.pkl
  wb:
    <<: *wandb_defaults

third_stage_ces_vep:
  <<: [*defaults, *stage3_vep_spec]
  output_dir: outputs/3_ces_vep
  model:
    <<: *model_defaults
    finetune_on: outputs/2_ces/model.pkl
  wb:
    <<: *wandb_defaults

third_stage_fin_gsw:
  <<: [*defaults, *stage3_gsw_spec]
  output_dir: outputs/3_fin_gsw
  model:
    <<: *model_defaults
    finetune_on: outputs/2_fin/model.pkl
  wb:
    <<: *wandb_defaults

third_stage_fin_fao:
  <<: [*defaults, *stage3_fao_spec]
  output_dir: outputs/3_fin_fao
  model:
    <<: *model_defaults
    finetune_on: outputs/2_fin/model.pkl
  wb:
    <<: *wandb_defaults

third_stage_fin_hsb:
  <<: [*defaults, *stage3_hsb_spec]
  output_dir: outputs/3_fin_hsb
  model:
    <<: *model_defaults
    finetune_on: outputs/2_fin/model.pkl
  wb:
    <<: *wandb_defaults

third_stage_fin_vep:
  <<: [*defaults, *stage3_vep_spec]
  output_dir: outputs/3_fin_vep
  model:
    <<: *model_defaults
    finetune_on: outputs/2_fin/model.pkl
  wb:
    <<: *wandb_defaults

veps_test:
  <<: *defaults
  output_dir: outputs/vep_test_fb
  training:
    <<: *training_defaults
    total_updates: 50
    batch_size: 16
  dataset:
    splits:
      train: train
      dev: dev
      test: test
    name: data/vep/vep_vwt-ud
  model:
    <<: *model_defaults