program: src/train.py
method: bayes
metric:
  name: validation/LAS
  goal: maximize

parameters:
  config:
    values: ['hyperpar_tuning']
  lr_model:
    distribution: uniform
    min: 1e-5
    max: 1e-3
  lr_classifier:
    distribution: uniform
    min: 1e-5
    max: 1e-3
  weight_decay:
    distribution: uniform
    min: 0.0
    max: 0.1
  warmup_rate:
    distribution: uniform
    min: 0.0
    max: 0.2
  dropout:
    distribution: uniform
    min: 0.0
    max: 0.5
  layer_dropout:
    distribution: uniform
    min: 0.0
    max: 0.5
  scheduler:
    values: ['cosine', 'noam', 'none']