program: src/train.py
method: bayes
metric:
  name: validation_LAS
  goal: maximize

parameters:
  config:
    values: ['hpt_test']
  lr_model:
    distribution: uniform
    min: 1e-6
    max: 1e-4
  lr_classifier:
    distribution: uniform
    min: 1e-5
    max: 1e-3
  weight_decay:
    distribution: uniform
    min: 0.0
    max: 0.01
  warmup_rate:
    distribution: uniform
    min: 0.0
    max: 0.2
  dropout:
    distribution: uniform
    min: 0.0
    max: 0.5
  layer_dropout:
    distribution: uniform
    min: 0.0
    max: 0.5
  scheduler:
    values: ['cosine', 'noam', 'none']

early_terminate:
  type: hyperband
  min_iter: 1
  eta: 3